version: '3.9'

services:
  server:
    image: ikosh/server
    environment:
      TOKEN: ${TOKEN}
      DB: ${DB}
      PORT: 80
    ports:
      - 3030:80

  agent:
    image: ikosh/agent
    environment:
      AGENT_PORT: 80
      SERVER_HOST: server
      SERVER_PORT: 80
    depends_on:
      - server
    deploy:
      replicas: 3
